#!/usr/bin/env python3
"""Automated Assembly Documentation Generator (Sol 5.6 Max).

Matches assembly_steps against component metrics and writes a scannable
interactive checkout manual tracking physical production dependency states.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


class AssemblyDocAgent:
    """Compile an interactive Markdown assembly runbook from BOM data."""

    def __init__(self, workspace_dir: str | None = None) -> None:
        self.workspace = (
            workspace_dir
            if workspace_dir is not None
            else str(Path(__file__).resolve().parent)
        )

    def compile_markdown_manual(
        self, bom_data: dict[str, Any] | None = None
    ) -> str | None:
        if bom_data is None:
            bom_path = os.path.join(self.workspace, "specs/bom.json")
            if not os.path.exists(bom_path):
                print("[Doc Agent] Hold: 'specs/bom.json' missing.")
                return None
            with open(bom_path, "r", encoding="utf-8") as handle:
                bom_data = json.load(handle)

        project_title = bom_data["project_metadata"]["project_name"]
        id_to_name = {
            c["component_id"]: c["name"] for c in bom_data.get("components", [])
        }

        # Load optional tolerance / slicing context for scannable callouts
        tol_path = os.path.join(self.workspace, "outputs/config/tolerance_matrix.json")
        tolerance_ids: set[str] = set()
        if os.path.exists(tol_path):
            with open(tol_path, "r", encoding="utf-8") as handle:
                tol = json.load(handle)
            tolerance_ids = {
                c["component_id"] for c in tol.get("components", [])
            }

        md_content = f"""# Physical Assembly Manual: {project_title}

Generated by Sol 5.6 Max Assembly Doc Agent. Verify steps sequentially to preserve fit tolerances.

## Component Checklist Before Beginning

Verify all FDM prints are finished and cleaned before opening assembly tracks:

"""
        for comp in bom_data["components"]:
            mfg = comp["manufacturing"]
            tol_flag = (
                " — **tolerance-critical**"
                if comp["component_id"] in tolerance_ids
                or mfg.get("requires_tolerance_tuning")
                else ""
            )
            md_content += (
                f"- [ ] **{comp['name']}** (Qty: {comp['quantity']}) — "
                f"*Material: {mfg['material_hint']}* / "
                f"*Profile: {mfg['mechanical_profile']}*{tol_flag}\n"
            )

        md_content += "\n## Step-by-Step Assembly Tracking Pipeline\n"

        steps = bom_data.get("assembly_steps") or []
        if not steps:
            md_content += "\n- [ ] *No step details provided in original brief.*\n"
        else:
            for step in steps:
                md_content += f"\n### Phase {step['step_number']}\n"
                md_content += f"- [ ] {step['instruction']}\n"
                prereqs = step.get("prerequisite_components") or []
                if prereqs:
                    labeled = [
                        f"`{cid}` ({id_to_name.get(cid, 'unknown')})"
                        for cid in prereqs
                    ]
                    md_content += (
                        f"  - **Required Items Ready:** {', '.join(labeled)}\n"
                    )

        md_content += """
## Post-Assembly Validation

- [ ] Confirm all tolerance-critical interfaces seated without forced deflection beyond design clearance
- [ ] Re-check hole compensation offsets against `outputs/config/tolerance_matrix.json`
- [ ] Archive this checklist with the build lot / print batch ID
"""

        out_dir = os.path.join(self.workspace, "outputs/config")
        os.makedirs(out_dir, exist_ok=True)
        doc_path = os.path.join(out_dir, "ASSEMBLY_MANUAL.md")
        with open(doc_path, "w", encoding="utf-8") as handle:
            handle.write(md_content)

        print(f"[Doc Agent] Interactive assembly runbook compiled at: {doc_path}")
        return doc_path


if __name__ == "__main__":
    doc_gen = AssemblyDocAgent()
    doc_gen.compile_markdown_manual()
